import { useGoogleReCaptcha } from 'react-google-recaptcha-v3'
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { executeRecaptcha } = useGoogleReCaptcha();

  async function handleSubmit(ev) {
    ev.preventDefault();
    if (!executeRecaptcha) {
      console.log('Execute recaptcha not yet available');
      return;
    }

    try {
      const token = await executeRecaptcha('yourAction');
      console.log(token)
      const { name, email } = ev.currentTarget.elements;
      const response = await fetch("/api/questionnaire/send", {
        method: "POST",
        headers: {
          Accept: "application/json",
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ name: name.value, email: email.value }),
      });
      const result = await response.json();
      console.log(result)
    } catch (err) {
      console.log(err);
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <form onSubmit={handleSubmit}>
          <input type="text" name="name" placeholder="Enter your name" />
          <input type="email" name="email" placeholder="Enter your email" />
          <button type="submit">Save</button>
        </form>
      </main>
    </div>
  );
}
